### ISSUE TITLE
CONTATO

### ISSUE THREAD

**Issue by andrebetiolo** [danielfilho/danielfilho.github.io#22]
Faaaaaaaaaaaaalaaaaaaaaaa Daniel, tudo bem? acho você um cara bacana e gostaria de saber se tem alguma possibilidade de fazer uma visita aqui em Ji-Paraná/RO com tudo pago dentre os próximos messes e de quebra fazer uma palestra em um FDS? estou querendo fazer um evento de desenvolvimento de software e gostaria da sua presença se fosse possível. grato.

**Comment by danielfilho** [comment]
fala @andrebetiolo, tudo bem?

cara, não conheço RO ainda, mas confesso que morro de vontade de conhecer. mas infelizmente eu dei uma parada com palestras há quase dois anos :disappointed: 

tenho perdão nessa? :grimacing:

**Comment by andrebetiolo** [comment]
Está perdoado, eu li o seu artigo na época falando sobre a modinha das palestras e etc, mas como você falou, fazia tempo que não fazia e também com o home office agora achei que poderia ter uma possibilidade. É porque como comentei acho você um cara muito gente boa e ficaria feliz se pudesse, mas de qualquer forma obrigado pela resposta.

**Comment by danielfilho** [comment]
valeu demais @andrebetiolo. valeu por compreender :)
