### ISSUE TITLE
POST: Por que estou deixando o Google?

### ISSUE THREAD

**Issue by hlrossato** [danielfilho/danielfilho.github.io#24]
Muito bom seu texto. Achei interessante e me surgiu uma dúvida. Sou desenvolvedor também e já tentei por várias vezes usar o Firefox porém acabo voltando para o Chrome pois uso para desenvolver e uso pessoal e acho o Firefox bem mais lento que o Chrome. Você usa algum hack ou alguma configuração diferente no FF ou usa o padrão (out-of-the-box)?? 

Até mais. Parabéns pelo texto.

**Comment by danielfilho** [comment]
uso o padrão mesmo @hlrossato.

já tem alguns meses que o Firefox não está mais atrás do Chrome para o desenvolvedor. fato que eles tem um time invejável, mas o Firefox está correndo cada vez mais. e em gerenciamento de memória e recursos, o FF já passou a rasteira no concorrente :smile:
