### ISSUE TITLE
CONTATO

### ISSUE THREAD

**Issue by danimaaan** [danielfilho/danielfilho.github.io#26]
Bom dia Daniel,

Estava vendo, agora pela manhã sua palestra no Youtube do Congresso E-Commerce Brasil 2014 sobre App nativo ou Web App e realmente penso que usamos o operador lógico errado mesmo. Particularmente eu usava o "OU" e após sua palaestra vou usar o "E"... kkkkkk

Gostaria de parabenizá-lo pela palestra e pelos links que você deixou:

http://adamkaplan.me/grid/
http://www.lukew.com/resources/mobile_first.asp

Sei que o mundo do desenvolvimento é muito dinâmico e como já estamos em 2016, caso tenha outras fontes e queira compartilhar comigo ficaria extremamente grato.

Mais uma vez obrigado pela palestra. Foram apenas 30 minutos porém muito esclarecedor.

**Comment by danielfilho** [comment]
valeu demais @danimaaan, sempre bom saber que podemos ajudar ;)
